// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxVj0tR4UWmN3yksuHyO7HoXNmzEUw5Dw',
    appId: '1:288130798940:web:684ddbe538045f5b599d99',
    messagingSenderId: '288130798940',
    projectId: 'unihealthai-11fe2',
    authDomain: 'unihealthai-11fe2.firebaseapp.com',
    storageBucket: 'unihealthai-11fe2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'TODO: Add your Android API Key',
    appId: 'TODO: Add your Android App ID',
    messagingSenderId: 'TODO: Add your Messaging Sender ID',
    projectId: 'TODO: Add your Project ID',
    storageBucket: 'TODO: Add your Storage Bucket',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'TODO: Add your iOS API Key',
    appId: 'TODO: Add your iOS App ID',
    messagingSenderId: 'TODO: Add your Messaging Sender ID',
    projectId: 'TODO: Add your Project ID',
    storageBucket: 'TODO: Add your Storage Bucket',
    iosBundleId: 'TODO: Add your iOS Bundle ID',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'TODO: Add your macOS API Key',
    appId: 'TODO: Add your macOS App ID',
    messagingSenderId: 'TODO: Add your Messaging Sender ID',
    projectId: 'TODO: Add your Project ID',
    storageBucket: 'TODO: Add your Storage Bucket',
    iosBundleId: 'TODO: Add your macOS Bundle ID',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'TODO: Add your Windows API Key',
    appId: 'TODO: Add your Windows App ID',
    messagingSenderId: 'TODO: Add your Messaging Sender ID',
    projectId: 'TODO: Add your Project ID',
    storageBucket: 'TODO: Add your Storage Bucket',
    authDomain: 'TODO: Add your Auth Domain',
  );
}